### ISSUE TITLE
access to videos

### ISSUE THREAD

**Issue by mshooter** [cvoelter/dog_exploration_3Dtracking#1]
Hi, 
great work! 
I am a bit confused where can I get the videos?

**Comment by cvoelter** [comment]
Hi, thanks a lot! 
The videos are not publicly available (apart from the supplementary video: Voelter_Staric_Huber_ESM_VideoS1.mp4), sorry. The repository includes all data files and R scripts but not the videos.

**Comment by mshooter** [comment]
Will it be available at some point? 
it would be great if it was publicly available
